### ISSUE TITLE
支持钉钉，微信，飞书消息发送？

### ISSUE THREAD

**Issue by melin** [dromara/SMS4J#1]
现在告警要求支持钉钉，微信，飞书其中之一比较多，是否考虑统一支持掉？

**Comment by fengruge** [comment]
后续可能会添加相应的插件支持，但是主项目始终围绕短信展开哦

**Comment by Hi-Mr-Wind** [comment]
规划之初，sms4j只是一个短信的融合发送工具，旨在降低发送短信这件小事占用程序员的时间，但是现在大家都反馈通知类相关的，比如钉钉，微信，飞书，邮件，后续的计划中可能会逐步的将这些以额外插件的形式引入，（当然也可能是全新的仓库）还有用户在反馈服务端主动通知的问题，现在已经有计划做一个中间件（已经开始着手了）来吧服务端主动推送这件事也简化下来

**Comment by Hi-Mr-Wind** [comment]
目前已经接入了OA，请关注

**Comment by Hi-Mr-Wind** [comment]
后续会开始一个全新的中间件项目（sms4j不会停止维护），在此基础上，强化集成通知能力，敬请关注
