### ISSUE TITLE
业务中有多个短信模板如何设置？

### ISSUE THREAD

**Issue by YOHN89** [dromara/SMS4J#10]
看文档里面写短信模板设置的时候，时候只能设置一个模板。但是实际业务中往往不止一个短信模板，通常会有多个模板，比如：1发送短信验证码；2，发送未读消息等通知提醒；3，发送礼品卡券；等等。
只能设置一个的话基本上没啥用。

**Comment by branchen** [comment]
如果你想在某个环节动态的改变配置中的值，可以随时通过SupplierFactory.getAlibabaConfig()获取阿里云的单例配置对象，并且修改它的值，但是要注意的是， 如果你修改了阿里云配置的值在发送短信前必须至少调用一次SmsFactory.refresh(SupplierType.ALIBABA);方法进行配置刷新。

**Comment by branchen** [comment]
建议看下文档-API详解：https://wind.kim/doc/api/#%F0%9F%93%A8%E6%A0%87%E5%87%86%E7%9F%AD%E4%BF%A1
