### ISSUE TITLE
营销短信如何使用

### ISSUE THREAD

**Issue by CrushDope** [dromara/SMS4J#11]
业务中存在营销类短信，模板中不需要配置参数，这种应该如何使用呢

**Comment by branchen** [comment]
传营销模板id, 变量值放空。

**Comment by branchen** [comment]
建议看下文档的 -API详解。https://wind.kim/doc/api/#%F0%9F%93%A8%E6%A0%87%E5%87%86%E7%9F%AD%E4%BF%A1

**Comment by Hi-Mr-Wind** [comment]
> 建议看下文档的 -API详解。https://wind.kim/doc/api/#%F0%9F%93%A8%E6%A0%87%E5%87%86%E7%9F%AD%E4%BF%A1

感谢帮忙回复
