### ISSUE TITLE
咨询一些问题

### ISSUE THREAD

**Issue by zhu-mingye** [dromara/SMS4J#4]
1. 厂商名称能否改为英文
2. 如果配置为数据库方式, 需要另加一个厂商字段 此外前端的值需要与枚举值匹配 同样存在(1)的问题 ,不是特别好
3. 引用(2), 无法和其他告警插件达到同一结构 ,对于 钉钉,企微,飞书等告警类型其实是不需要这个字段的 , 目前我这边实现钉钉,企微,飞书告警类型 所有参数存储在 params 字段中 存储为json, 另一个字段type 存储告警类型,
4. 针对短信多了个字段我这边存储在了 params 中, 但是在yml文件中 需要指定  supplier-field-name 此处不能取值于json字段中得某一个key,
5. 针对2,3,4中的描述 可否将 supplier-field-name 放出来做一个增强的自定义配置,由用户自己配置该字段的取值

**Comment by fengruge** [comment]
这是个很好的提议，最初时候的枚举name字段其实并没有实质的作用，只是后来随着功能的增加添加了这一部分，对于数据库配置的方式，其实我个人还不太满意，我现在更倾向于自定义配置方式，因为他完全的自由，不限制你数据的来源，只关注结果，不过sql形式的配置我们后续也会继续的优化，感谢您的提议

**Comment by Hi-Mr-Wind** [comment]
sql配置中总是要告诉框架，他需要去哪里找到什么样的数据作为哪个厂商的配置，现在的配置项还是太多了，后续我们会寻求一种新的方式来优化sql配置的形式，或者说尽量把自由度交还给用户。
你的这种形式还是更建议使用自定义形式配置，最为自由和方便

**Comment by Hi-Mr-Wind** [comment]
如果你对这里有什么好的建议或者方案，也欢迎加入到我们

**Comment by zhu-mingye** [comment]
> 

自定义形式配置是指 builder的那种吗?  如果使用这种 配置文件是不是就不需要配置了???

**Comment by Hi-Mr-Wind** [comment]
是的，你只需要build 出来一个相应的配置对象，然后set给工厂他就不再需要读取其他的配置了，包括yml，而且他只关注你给与他的数据，不关注数据的来源和方式
